[package]
name = "sh_lib"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
chrono = "0.4.42"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.20.0", features = ["v4", "v5"] }

[build-dependencies]
prost-build = { version = "0.14.3" }
