[package]
name = "sh_therm_emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rand = "0.9.2"
sh_lib = { version = "0.2.0", path = "../sh_lib" }
tokio = { version = "1.48.0", features = ["full"] }
