[alias]
lint = "clippy --all --all-targets -- -D warnings"
test-lib = "test --package=sh_lib"
test-ex = "test --package=sh_ex"
fmt-check = "fmt -- --check"
br = "build --release"
clean = "rm -rf target"
